### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by jvocib** [wannesm/adsphd#10]
Hello,

Thanks very much for the template, it has been quite useful. There is one issue I cannot seem te resolve: I'm having problems with the glossary.

This is the code in the thesis.tex file. However, the glossary does not show up. Any suggestions how this could be resolved?
Many thanks.
Joris

% To avoid problems, do NOT change the layout of the following two
% commands
\let\printglossaryorig\printglossary
\renewcommand{\printglossary}{%
  \renewcommand{\glossaryname}{\glossname}
  \cleardoublepage%
  \printglossaryorig\chaptermark{\glossname}}

\usepackage{glossary}
    \makeglossary
    \glossary{name=MD,description=molecular dynamics}

% Specify the .bib file
\bibliography{allpapers}

% Bibtex style
\bibstyle{abbrv}
\bibstyle{acm}

% Own commands
\InputIfFileExists{defs} % defs.tex, contains own preamble settings

% }{}}}  <-- Preamble

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%\makefrontcover
\makefrontcoverXII

\maketitle

\frontmatter % to get \pagenumbering{roman}

%\includepreface{preface}
%\includeabstract{abstract}
%\includeabstractnl{abstractnl}

% To create a list of abbreviations, there are 2 options
% 1. manual creation and inclusion of this file
%    \includeabbreviations{abbreviations}
% 2. automatic generation via the glossary package

```
%\printglossary
```

\printglossary

**Comment by wirth6** [comment]
Adding a makindex command as "mtuandat" put it to TexMaker's user commands was very helpful with abbreviations. However symbols are still not showing up. Do you have to have another makeindex command for that?
