### ISSUE TITLE
co-tutorship layout

### ISSUE THREAD

**Issue by pagliasofia** [wannesm/adsphd#20]
Good Morning! 
I am compiling in Latex a `joint phd diploma' thesis, hence there must be the logos and names of the two institutions (in my case, Bicocca University of Milan and KUL), + both names of faculties and deparments, and supervisor 7 co-supervisor, of course. 
I've made a cover by myself, however I wonder if there are common guidelines already available with regard to co-tutored phd thesis.

Thanks a lot and in advance for any suggestion and help, 
best wishes 
sofia p.

**Comment by GiulioBen** [comment]
I know that the discussion is closed, 

but

I slightly modified the class file to add the co-promoters (aka co-supervisor).
The new command is 
\cosupervisor{Dr. Mamma Mia}{}

It's my first time using latex, so I hope I did nothing wrong. You can find the file attached below. (rename to adsphd.cls)  Remember to put it into the local tex folder and to remove all the auxiliary files (lox, aux, lof, lot etc) before recompiling.

[adsphd.txt](https://github.com/wannesm/adsphd/files/1907878/adsphd.txt)

Good luck with the dissertation :)

**Comment by pagliasofia** [comment]
​Merci!

sofia p,
-- 
*dr. Sofia Pagliarin, phd*
Urban and Territorial Studies

Post-doc Researcher
Bamberg Graduate School of Social Sciences (BAGSS)
Otto-Friedrich-Universität Bamberg, Germany

Swiss Federal Research Institute WSL
Landscape Ecology Research Unit
CONCUR project <https://www.wsl.ch/de/projekte/concur.html>
#TruthForGiulio
<https://www.change.org/p/justiceforgiulio-veritapergiulio-paologentiloni-federicamog?recruiter=411837158&utm_source=share_petition&utm_medium=copylink>

<https://www.change.org/p/justiceforgiulio-veritapergiulio-paologentiloni-federicamog?recruiter=411837158&utm_source=share_petition&utm_medium=copylink>
--------------
sofia.pagliarin@wsl.ch
pagliarin.sofia@gmail.com
*skype*: pagliasofia
mob. (IT) +39 340 52 81 635
