### ISSUE TITLE
build a single chapter

### ISSUE THREAD

**Issue by saroele** [wannesm/adsphd#28]
this is a basic question I guess: how to build a pdf of a single chapter?

**Comment by saroele** [comment]
Ok, works well indeed with the make file in a chapter.  Thanks

**Comment by particle2015** [comment]
Hello,

This might sound stupid about "Using make and other utility scripts": How I can run "make" script? I have texwork, texmaker, but I do not know where. should I use python? or should I run from command line?

Is it a line of code in chapterx? like "make xxx"?
I found this "Makefile" file in the main directory but I do not know how to use.    @saroele  @tillnagel .
