### ISSUE TITLE
Todo notes are visible in the 'tothejury' version

### ISSUE THREAD

**Issue by tassos** [wannesm/adsphd#36]
When using the tothejury version for sending my thesis to the jury, I noticed that the todo notes were still visible, which is not consistent with what is written in the Readme. I fixed that in my fork (https://github.com/tassos/adsphd/commit/f63cc35d7fb47309760e417a3fc2c2f7c39b01d1), but as I am waiting for a pull request to be accepted, I will wait with making a new pull request with this one.

Just reporting it here, so that people that want to send their thesis to the jury are aware that their todo notes will be visible.

**Comment by wannesm** [comment]
Notes are not part of the style file anymore. You can now include your own preferred notes package.
