### ISSUE TITLE
How to set a picture for the cover

### ISSUE THREAD

**Issue by tassos** [wannesm/adsphd#37]
Is there a way to add a figure on the cover using the current template? If not, what would be the best way to do so?

**Comment by tassos** [comment]
Okay, in the end I made a new text box between the title and authors name.

Would it make sense to pass a cover image as an option when calling the documentclass? It might be easier, although the author would still need to fiddle a bit with the size of the text box.

**Comment by wannesm** [comment]
An explanation of how to do this has been added to the manual chapter.
