### ISSUE TITLE
How to create a bibliography per chapter?

### ISSUE THREAD

**Issue by saroele** [wannesm/adsphd#38]
Hi all,

I want to create a bibliography by chapter.  How can I do this with the adsphd template?
I found this resource on the web, but I fear it's not compatible with the way the template handles the bibliography: http://wiki.davidhaberthür.ch/latex#chapterbib

Thanks! 
Roel

**Comment by nnabiollahi** [comment]
Did you found out how to fix the bibliography per chapter, using chapterbib?
I have concluded that the problem is each file for chapter is in its own folder.

**Comment by saroele** [comment]
Hi,

yes, I graduated in the mean time!
I figured out how to do it.  It's not complicated once you know :-)

You have to create specific refsections, and when you call ``\printbibliography``, only the citations within the current refsection will be put.   Here are the commands I used::
    
    \begin{refsection}

    Here comes your chapter

    \section{Bibliography}
    \printbibliography[heading=none]
    \end{refsection}

**Comment by herrmann-github** [comment]
Hi,

as I understand saroele's suggestion only works when using biber, right?

I am using the bibunit package to have several bibliographies in my document. The bibunit package creates an aux file for every bibunit section. The filename pattern for those files is buN.aux, where N is a number from 1 till number of bibunit sections. 

I was wondering if there is an easy way to modify the makefile to that it would automatically call bibtex with all buN.aux files.

Thanks!
