### ISSUE TITLE
List of Symbols not showing in the pdf

### ISSUE THREAD

**Issue by wirth6** [wannesm/adsphd#46]
Hi,

This is my first post here, so I hope I will be able to give all necessary details, so that someone can help me. My problem is that the List of symbols is not showing up in my pdf, even if I don't modify the downloaded package in any way, just unzip it, and compile it with a latex editor.

I'm using Windows 7, and a latex editor called TexMaker. The chain of commands I use to create the pdf is the following:

1. pdflatex -synctex=1 -interaction=nonstopmode %.tex
2. bibtex %
3. makeindex -s %.ist -t %.nlg -o %.nls -t %.glg -o %.gls %.nlo %.glo
4. pdflatex -synctex=1 -interaction=nonstopmode %.tex
5. pdflatex -synctex=1 -interaction=nonstopmode %.tex

This is based on a description I found somewhere when I was trying to solve a problem of the List of Abbreviations not showing up. Now that list is in my pdf, but unfortunately the list of symbols is still not there. I hope there will be someone on this forum who can help me.

**Comment by Koris** [comment]
It seems you have the wrong command for the nomenclature package (which handles the list of symbols). See https://trello.com/c/hmWz2n1u/20-nomenclature for a solution.

**Comment by wirth6** [comment]
Thank you, I added the commands corresponding to Make nomenclature and Show nomenclature to the command chain, and now the List of Symbols is finally showing up.
