### ISSUE TITLE
In-text citations

### ISSUE THREAD

**Issue by marloncalispa** [wannesm/adsphd#48]
Hi, I am new in this latex templates so, my question might be basic.

I would like to use the template, but I want to use in-text citations instead of numbers, like this:

'Latex is difficult (Someone et al., 1914).'

and then list them in the References section.

Is it possible to achieve it using the current template, I tried to use the natbib package but I am not clear how to adapt it.

**Comment by johannesbottcher** [comment]
Crosspost http://tex.stackexchange.com/q/285656/37907
