### ISSUE TITLE
side-by-side figures

### ISSUE THREAD

**Issue by goat-anti-rabbit** [wannesm/adsphd#49]
The adsphd template uses the deprecated packages subfig and subfigure. I tried to put figures side by side, but did not manage to. If I want to use the newer subcaption package, I get complaints about incompatibilities.

Is there a way to either: 
- simply put figures side by side using the adsphd as it is
- use the subcaption package without errors

Many thanks
Rik

**Comment by wannesm** [comment]
You can comment out lines 508-514 in adsphd.cls. Ideally, non-crucial packages such as subfig(ure) should be removed from the class file permanently. We're open to pull requests or requests to be collaborator :-)
