### ISSUE TITLE
! LaTeX Error: File `mfirstuc.sty' not found.

### ISSUE THREAD

**Issue by Bailusha** [wannesm/adsphd#50]
I just downloaded the whole thing today and only changed the names on the front page but when I try to compile I get this error: 
! LaTeX Error: File `mfirstuc.sty' not found.

Can anyone help me with this?

Thanks

**Comment by tassos** [comment]
It seems that the mfirstuc is a dependency for the 'glossaries' package, which is used in this project. Can you try to install the glossaries package and try again?

http://www.ctan.org/tex-archive/macros/latex/contrib/glossaries/

**Comment by tassos** [comment]
Did it solve the issue? If yes, can you mark this issue as closed?
