### ISSUE TITLE
Bibliography back-references

### ISSUE THREAD

**Issue by orestemadia** [wannesm/adsphd#51]
Hello,
when I started to work on my thesis I decided to enter manually the bibliography in each chapter.
Now the thesis is ready and corrected, but I noticed utterly annoying back-references after compilation.
For example:
[1] Y. Taur, and E. Nowak CMOS devices below 0.1 μm: how high will
performance go? IEEE Proc. IEDM, 215-218 (1997) pages 3

I have been trying for days to get rid of this awful thing, but couldn't find any command.
Please help.

**Comment by wannesm** [comment]
Do you have `backref` or `pagebackref` in the options for adsphd.cls? Remove those.

If that doesn't work, comment out the lines in adsph.cls that contain `\RequirePackage{backref}` or `\RequirePackage{backref}`.

ps. backref is not part of the current adsphd.cls version anymore

**Comment by orestemadia** [comment]
Hi,
before writing this threat I went to look for backref and pagebackref in the file and comment whatever I could.
Now by commenting \RequirePackage{backref} the quote "pages" is gone, but the backreferences to the pages are still there.
Now it looks like:
[1] Y. Taur, and E. Nowak CMOS devices below 0.1 μm: how high will
performance go? IEEE Proc. IEDM, 215-218 (1997) 3

which is better, but might be misleading.
Thanks a lot.
Anymore suggestions?

**Comment by orestemadia** [comment]
Fixed !
