### ISSUE TITLE
Issues with tikz image externalization

### ISSUE THREAD

**Issue by giulianobernardi** [wannesm/adsphd#52]
Hi guys,
I'm using the `tikz` package for my images, but it seems that the template creates some problems when externalizing (i.e. creating a PDF file from the `tikz` image to speed up the inclusion when compiling the whole template) `tikz` images.

You can see the correct and wrong outcomes here:

[Correct.pdf](https://github.com/wannesm/adsphd/files/390447/Correct.pdf)
[Wrong.pdf](https://github.com/wannesm/adsphd/files/390446/Wrong.pdf)

Do you have any idea of what causes this clash?

**Comment by wannesm** [comment]
Tikz externalize uses some tricks to only show one image while keeping all the other settings when generating an image. Other packages such as `crop` and `textpos` use other tricks that Tikz is not aware of and clashes with the Tikz tricks. You need to deactivate crop and empty list of textpos for tikz externalize to work.

If you change the thesis.tex file as indicated below it should work (don't forget to delete all images to regenerate them):

```
...
\usepackage{amssymb,amsthm}
\usepackage{amsmath}

% Code where you setup tikz
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize

% Deactivate crop symbols when using tikz externalize
\tikzifexternalizing{ \crop[off]}{}

\makeatletter
\def\cleartextposbox{\global\setbox\TP@holdbox\vbox{}}
\makeatother



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\makefrontcoverXII
% Clear boxes used on the front page as they should have been printed by now
\cleartextposbox

...
```

**Comment by giulianobernardi** [comment]
Thanks for the reply @wannesm 
I had already noticed that `crop` was causing some troubles, such as some problem with inverse sync between my tex editor and the PDF viewer I'm currently using, so I have stopped using some of the template options yielding the draft mode.
That, however, just solves the clash between `external` and `crop`.

Your solution for `textpos` does the trick; one little detail, the command `\cleartextposbox` should be placed after `\maketitle` and `\frontmatter`, since I guess they also contribute to fill the list of `textpos`

**Comment by wannesm** [comment]
That's correct.
