### ISSUE TITLE
Manually generated list of symbols included twice

### ISSUE THREAD

**Issue by wettes** [wannesm/adsphd#56]
I have my own (manually generated) list of symbols in "symbols.tex", which I put in the directory "/chapters/symbols/". As a test, this file contains only one symbol and is given by:

\chapter{List of Symbols}
\nomenclature[B]{$a$}{test}
\cleardoublepage

When I start from the current adsphd-template and try to add my list of symbols by commenting out the line: 
\includenomenclature{symbols}

then, thesis.pdf contains 2 lists of symbols: 1 empty list of two pages having only "List of Symbols" as header followed by my actual "symbols.tex" symbol list (result: see attached file). 
In addition, there is only one entry in the table of contents for "List of Symbols" and the page refers to the empty list of symbols.
Any idea what I am doing wrong ?
[thesis.pdf](https://github.com/wannesm/adsphd/files/400316/thesis.pdf)

**Comment by wannesm** [comment]
The \printnomenclature command in thesis.tex generates the symbols chapter. Make sure to comment out that code if you don't want it generated. Commit 909feb8 also fixes an issue causing the list of symbols not to appear in the TOC.
