### ISSUE TITLE
Hyperref footnotes broken by setspace

### ISSUE THREAD

**Issue by Allan2Ring** [wannesm/adsphd#61]
Hyperref's footnote links refer to the title page. This seems to be caused by the package setspace, which is loaded after the hyperref in adsphd.cls. 

Suggested solution: move the following from lines 684-685 to lines 487-488 in adsphd.cls.
`% To easily change line spacing`
`\RequirePackage{setspace}`

**Comment by robindecroon** [comment]
This also solved my problem. Thanks for the solution.

**Comment by wannesm** [comment]
Thanks, changed it in adsphd.cls.
