### ISSUE TITLE
In-text references

### ISSUE THREAD

**Issue by wirth6** [wannesm/adsphd#62]
Hi, I have some experience with latex, but not nearly enough to figure out this issue.

I would like to use some references in the body of my thesis (not just in the references part): the idea is that  at the end of the first chapter (Introduction), I'd have a breakdown of the content of the following chapters, and here I'd also like to list the publications each chapter was based on.

For this I tried to use the \bibentry command from the bibentry package, which included nothing.
I also tried to use the \fullcite command from the biblatex package, but it seems that the biblatex package is not working with the acm bibiliography style, which I am using, so that's also not a viable solution.

And at this point I'm out of ideas, and was hoping someone more knowledgeable in latex could help me.
(BTW I'm using windows 7, texmaker, and the chain of commands I use to create my pdf is the following:

pdflatex -synctex=1 -interaction=nonstopmode %.tex
bibtex %
makeindex -s %.ist -t %.nlg -o %.nls -t %.glg -o %.gls %.nlo %.glo
pdflatex -synctex=1 -interaction=nonstopmode %.tex
makeindex %.nlo -s nomencl.ist -o %.nls
pdflatex -synctex=1 -interaction=nonstopmode %.tex
makeindex %.nlo -s nomencl.ist -o %.nls|pdflatex -synctex=1 -interaction=nonstopmode %.tex
"C:/Program Files (x86)/Adobe/Reader 11.0/Reader/AcroRd32.exe" %.pdf)

Thank you in advance for any help.

**Comment by wannesm** [comment]
Although this is probably not relevant anymore for the original author, I'd recommend the biblatex package (e.g. \fullcite).
