### ISSUE TITLE
Bibliography layout different depending on source

### ISSUE THREAD

**Issue by jverbeke** [wannesm/adsphd#63]
Hi,

There are significant differences in the layout of sources depending on their type which make the manuscript less clean to read through:

![image](https://cloud.githubusercontent.com/assets/7404911/26829064/4b3e35b2-4ac4-11e7-9d25-47015173e51e.png)

I use different types of sources in my bibliography::

- article
- inproceedings
- inbook
- book
- PhDThesis
- misc
- mastersthesis

Some annoying layout differences are:
- some titles use for each word a capital, others don't
- some sources have titles in italic, other sources the conference
- sometimes year between brackets, sometimes not

Why is this? 
Do everybody just use this standard, or do you adapt it?
How can I best change this, without having to manually change each entry (which are close to 90)

Cheers,

Jon

**Comment by wannesm** [comment]
The template does not enforce any style. In thesis.tex it loads the default bibtex settings. You can change thesis.tex to use any bibtex or biblatex style you wish.

**Comment by wannesm** [comment]
See examples at:
https://www.sharelatex.com/learn/Bibtex_bibliography_styles
https://www.overleaf.com/latex/examples/tagged/bibliography
