### ISSUE TITLE
Duplicated section names

### ISSUE THREAD

**Issue by MrTheodor** [wannesm/adsphd#65]
It is rather a question and not a bug..
I am wondering how to solve the issue with the same labels per chapter, currently LaTeX complain about it and also \ref put wrong reference.
The issue is because I have in two or more chapters `Method` section that is labeled by `\label{sec:method}`; the easiest way is to make all labels unique but maybe someone knows a better solution?

**Comment by ThijsBoehme** [comment]
How could the compiler know which section you are actually referring to if you have two identical labels?

The only correct solution is to use unique labels.

**Comment by MrTheodor** [comment]
Of course; I was looking for some solution that will not required from me to edit all labels.
