### ISSUE TITLE
\citet  not working

### ISSUE THREAD

**Issue by ykvishal** [wannesm/adsphd#68]
Hi,

I am trying to use \citet so that I can use 'Author Name et al [reference number]' format. However, it seems that this is not compatible with adsphd.

Is there any other way to have Author Name and reference number with single command?

**Comment by wannesm** [comment]
The adsphd package does not load any bibliography packages. You can pick one yourself as it should work with most available options. For more advanced use such as \citet use natbib or biblatex (biblatex is already in the comments of thesis.tex).
