### ISSUE TITLE
Symmetric margins and binding

### ISSUE THREAD

**Issue by wirth6** [wannesm/adsphd#70]
Hi,

This might be a bit of an odd question, but I was looking at dissertations I presume were written with this template, and I see the same thing I see with my own pdf: the margins are the same for the even and the odd pages. I wonder if this could cause any problems when binding, as I would have assumed that odd pages should have a bigger margin on the left side, while even pages should have a bigger margin on the right side. Does anyone have any experience about this?

Thank you in advance for any help.

**Comment by Somya1986** [comment]
Can someone please answer this question? I am wondering the same as wirth6.

**Comment by wirth6** [comment]
I completely forgot that I had asked this question. But since then I have taken my dissertation to a printing service, and there was no problem at all with the margins. So I believe my question was answered in a sense.

**Comment by wirth6** [comment]
I live in Hungary, and the printing shop I used is also here, so the location probably would not be very helpful. But I would assume that print-shops in Leuven are just as competent, and so if it was not a problem here, it should not be a problem there either.

As far as I remember the box around the text was only there in the draft version, so once I added 'final' to class options, it was not a problem anymore.

**Comment by wannesm** [comment]
The text is indeed centered. For print shops this is typically no problem as a perfect bound is used and they can adapt this themselves by shifting the page.

When you would use a binding method such as saddle, comb or spiral bound, this would be different (and can be achieved by changing the settings for the geometry package in the template).
