### ISSUE TITLE
Undefined control sequence of \makefrontcoverXII

### ISSUE THREAD

**Issue by NorbertMagyar** [wannesm/adsphd#72]
Dearest latex template contributors,

I have just downloaded the template, as I am about to start writing my thesis.
I get this error by multiple means of compiling, without making any changes to the original files (make, ./run.py, Texmaker, etc.):

```
> ! Undefined control sequence.
> \makefrontcovergeneralXII ...sffamily \dtlifnumlt
> {\DTLrowcount {supervisor}...
> l.111 \makefrontcoverXII
```
I tried some debugging myself, however, I'm not really a Latex expert. Any ideas?

Thank you very much for putting this template together!

Norbert

**Comment by wannesm** [comment]
You might have an older LaTeX installation. The template requires a recent version of the datatool package (https://ctan.org/pkg/datatool?lang=en).

**Comment by NorbertMagyar** [comment]
Thanks a lot! It worked!
