### ISSUE TITLE
How to use pdf_tex in new version of template?

### ISSUE THREAD

**Issue by heleenfeh** [wannesm/adsphd#74]
I am trying to add a pdf_tex figure to a chapter: 
\begin{figure}[h]
\input{image/CV.pdf_tex}
\caption{Some caption}
\label{fig:CV}
\end{figure}

This doesn't work in the new template. The error I get is:
! LaTeX Error: File `image/CV.pdf_tex' not found, while the figure is there. 
I've plugged in my chapter into an older version of the template, and there it does work.

**Comment by ThijsBoehme** [comment]
[This question on StackOverflow](https://tex.stackexchange.com/questions/125324/including-pdf-tex-images-from-inkscape) suggests adding the `import` package when the image is in a subfolder (`image/` in your case), or adding `\graphicspath{{image/}}` to the preamble.

**Comment by heleenfeh** [comment]
Thanks for your suggestions. The import package is used and adding \graphicspath{{image/}} does not solve the problem. For other type of figures (.jpg, .png, ...) , I don't have a problem. It related to the fact that it is a .pdf_tex or that the \input is used.

**Comment by heleenfeh** [comment]
\import{chapters/chaptername/image/}{CV.pdf_tex} does the trick! 
Thanks a lot!
