### ISSUE TITLE
problem compiling references

### ISSUE THREAD

**Issue by Nathalievr** [wannesm/adsphd#77]
I have a problem with the references when I compile my file. I use MikTex 2.9.6643. I created a file allpapers.bib with Endnote. I use the code:

\includebibliography

\bibliographystyle{acm}
\bibliography{allpapers}

The file compiles, but in the log-file it is indicated that the references were not found. In the text they appear as [?]. The bibliography is not generated, as well as the table of contents, list of figures.

**Comment by wannesm** [comment]
Does the allpapers.bib file exists in the same directory? See https://www.overleaf.com/blog/532-creating-and-managing-bibliographies-with-bibtex-on-overleaf for more background on using bibtex.

**Comment by Nathalievr** [comment]
I used the wrong format in my allpapers.bib, but now it works again, thanks!
