### ISSUE TITLE
package inputenc error unicode character u262f

### ISSUE THREAD

**Issue by DriesDeKegel** [wannesm/adsphd#80]
I was able to compile (only the introduction) of my thesis.
However, just now I try to add the bibliography of the introduction.
And I got this error... no idea what is going on.

I already compiled again without bibliography (commented) but still same error.

How do I solve this error?

**Comment by wannesm** [comment]
This is not a problem with the package. You have a symbol in your bibtex file that is outside the range of the Unicode packages you load (inputenc). The problem is  probably still there because latex still has it in the temporary files. Remove the symbol or use another library for Unicode.
