### ISSUE TITLE
\bibtex database error

### ISSUE THREAD

**Issue by DriesDeKegel** [wannesm/adsphd#81]
Just recently I got this error as well:

"This bibtex, version 0.99d (...) the top-level auxiliary file: thesis.aux a level-1 auxiliary file: ... sum up of all the auxilary files:  I found no \bibdata command - while reading file thesis.aux, warning - i didn't find a database entry for ... etc.... "

how to solve this error?

**Comment by wannesm** [comment]
This is not related to the package but a general latex/bibtex error. Sounds like you're mixing bibtex and biber (biblatex generated code for biber that you are running with the bibtex binary). Best is to search https://tex.stackexchange.com (and remove all intermediate files).
