### ISSUE TITLE
Resizing for A4 Master's thesis

### ISSUE THREAD

**Issue by VDBram** [wannesm/adsphd#87]
Hi!

First of all, many thanks for this amazing template. 

As advised by the KUL Faculty of Science website, I'm planning on using the template for my Master's thesis. The thesis however would be A4-sized rather than the cropped format used in the template. Is there an easy way of modifying the document size without messing too much with the layout? (If it's not easy at all, please let me know and I will remove this question! :) )

Many thanks!
Bram

**Comment by wannesm** [comment]
I assume that by now the thesis is submitted but for future reference: The template hardcodes the official size for phd dissertations. I think the faculty of science might be referring to the master thesis latex template from the faculty of engineering sciences.
